apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 'product-service'
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/inf23056/sose-26-devops.git
    path: kubernetes/product-service
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: webshop
  syncPolicy:
    automated:
      enabled: true
