name: Publish

on:
  push:
    tags:
      - '*-service-[0-9]*.[0-9]*.[0-9]*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get service name and version
        id: service
        run: |
          REF_NAME="${GITHUB_REF##*/}"

          SERVICE="$(echo "${REF_NAME}" | sed 's/-[0-9]\+\.[0-9]\+\.[0-9]\+$//')"
          VERSION="$(echo "${REF_NAME}" | sed 's/^.*-\([0-9]\+\.[0-9]\+\.[0-9]\+\)$/\1/')"
          echo "service=${SERVICE}" >> "$GITHUB_OUTPUT"
          echo "version=${VERSION}" >> "$GITHUB_OUTPUT"

      - name: Print service and version
        run: |
          echo "Service: ${{ steps.service.outputs.service }}"
          echo "Version: ${{ steps.service.outputs.version }}"

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build \
            --build-arg SERVICE=${{ steps.service.outputs.service }} \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/${{ steps.service.outputs.service }}:${{ steps.service.outputs.version }} \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/${{ steps.service.outputs.service }}:latest \

      - name: Install Syft
        uses: anchore/sbom-action/download-syft@v0

      - name: Generate SBOM with Syft (CycloneDX)
        run: |
          syft ${{ secrets.DOCKERHUB_USERNAME }}/${{ steps.service.outputs.service }}:${{ steps.service.outputs.version }} \
            -o cyclonedx-json \
            --file sbom-${{ steps.service.outputs.service }}-${{ steps.service.outputs.version }}.cyclonedx.json

      - name: Install Grype
        uses: anchore/scan-action/download-grype@v6

      - name: Scan SBOM with Grype for CVEs
        run: |
          grype sbom:sbom-${{ steps.service.outputs.service }}-${{ steps.service.outputs.version }}.cyclonedx.json \
            --output table \
            --fail-on critical

      - name: Upload SBOM as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: sbom-${{ steps.service.outputs.service }}-${{ steps.service.outputs.version }}
          path: sbom-${{ steps.service.outputs.service }}-${{ steps.service.outputs.version }}.cyclonedx.json

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ steps.service.outputs.service }}:${{ steps.service.outputs.version }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ steps.service.outputs.service }}:latest